title: Tubrux
description: Code Vulnerability Analyzer for Java/Kotlin.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

baseurl: ""
url: "https://tubrux.github.io"
permalink: pretty